[package]
name = "teloxide"
version = "0.4.0"
edition = "2018"
description = "An elegant Telegram bots framework for Rust"
repository = "https://github.com/teloxide/teloxide"
documentation = "https://docs.rs/teloxide/"
readme = "README.md"
keywords = ["teloxide", "telegram", "telegram-bot", "telegram-bot-api"]
license = "MIT"
exclude = ["media"]
authors = [
        "Temirkhan Myrzamadi <hirrolot@gmail.com>",
        "Waffle Lapkin <waffle.lapkin@gmail.com>",
        "p0lunin <dmytro.polunin@gmail.com>",
        "Mishko torop'izhko",
        "Mr-Andersen",
        "Sergey Levitin <selevit@gmail.com>",
        "Rustem B. <bakirov.com@yandex.ru>",
        "Alexey Fedechkin <aleksey-fedechkin@rambler.ru>"
]

[badges]
maintenance = { status = "actively-developed" }

[features]
sqlite-storage = ["sqlx"]
redis-storage = ["redis"]
cbor-serializer = ["serde_cbor"]
bincode-serializer = ["bincode"]

frunk- = ["frunk"]
macros = ["teloxide-macros"]

native-tls = ["teloxide-core/native-tls"]
rustls = ["teloxide-core/rustls"]
auto-send = ["teloxide-core/auto_send"]
throttle = ["teloxide-core/throttle"]
cache-me = ["teloxide-core/cache_me"]

# currently used for `README.md` tests, building docs for `docsrs` to add `This is supported on feature="..." only.`,
# and for teloxide-core.
nightly = ["teloxide-core/nightly"]

full = [
    "sqlite-storage",
    "redis-storage",
    "cbor-serializer",
    "bincode-serializer",
    "frunk",
    "macros",
    "teloxide-core/full",
    "native-tls",
    "rustls",
    "auto-send",
    "throttle",
    "cache-me"
]

[dependencies]
teloxide-core = { version = "0.2.1", default-features = false }
teloxide-macros = { version = "0.4", optional = true }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

tokio = { version = "1.2", features = ["fs"] }
tokio-util = "0.6"
tokio-stream = "0.1"

reqwest = { version = "0.11", features = ["json", "stream"] }
log = "0.4"
lockfree = "0.5.1"
bytes = "1.0"
mime = "0.3"

derive_more = "0.99"
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
pin-project = "1.0"
serde_with_macros = "1.4"

sqlx = { version = "0.5", optional = true, default-features = false, features = [
        "runtime-tokio-native-tls",
        "macros",
        "sqlite",
] }
redis = { version = "0.20", features = ["tokio-comp"], optional = true }
serde_cbor = { version = "0.11", optional = true }
bincode = { version = "1.3", optional = true }
frunk = { version = "0.3", optional = true }

[dev-dependencies]
smart-default = "0.6.0"
rand = "0.8.3"
pretty_env_logger = "0.4.0"
lazy_static = "1.4.0"
tokio = { version = "1.2.0", features = ["fs", "rt-multi-thread", "macros"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[test]]
name = "redis"
path = "tests/redis.rs"
required-features = ["redis-storage", "cbor-serializer", "bincode-serializer"]

[[test]]
name = "sqlite"
path = "tests/sqlite.rs"
required-features = ["sqlite-storage", "cbor-serializer", "bincode-serializer"]
